version: "3.8"

services:

  postgres:
    image: postgres:11-alpine
    environment:
    - POSTGRES_DB:${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASS}
    ports:
    - "5432:5432" # for debugging db

  ipfs:
    image: ipfs/go-ipfs:v0.6.0
    ports:
    - "8100:8080" # gateway for debugging
    - "5001:5001" # API for debugging

  server:
    build: .
    image: aragon/ipfs-background-service
    command: yarn start:server:dev
    depends_on:
    - postgres
    - ipfs
    - loki
    ports:
    - "${SERVER_PORT}:${SERVER_PORT}"
    - "${SERVER_METRICS_PORT}:${SERVER_METRICS_PORT}" # for debugging metrics
    volumes:
    # speed up development by mounting some local directories with hot reload
    - ./packages/server/src:/app/packages/server/src
    - ./packages/server/test:/app/packages/server/test
    - ./packages/shared/build:/app/packages/shared/build
    env_file:
    - .env
    logging: &loki
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        # required to be compatible with k8s metrics
        loki-external-labels: container_name={{.Name}},app=ipfs-background-service


## Monitoring containers below

  prometheus:
    image: prom/prometheus
    depends_on:
    - server
    volumes:
    - ./monitoring/prometheus:/etc/prometheus

  loki:
    image: grafana/loki
    ports:
    - "3100:3100" # required for loki plugin to work

  grafana:
    image: grafana/grafana
    depends_on:
    - prometheus
    - loki
    ports:
    - "5000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
    - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
