name: Staging CI/CD
on:
  push:
    branches:
    # Executes on any non master commit, but release and deploy steps only run on development
    # This is useful to see if tests are passing during PR review
    - '**'
    - '!master'
    paths-ignore:
    - 'monitoring/**'
env:
  # This is a base repository and we use ${GITHUB_SHA} to set the version of the container
  REPO: docker.pkg.github.com/aragonone/ipfs-background-service/development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
    - run: .github/scripts/docker-build.sh $REPO ${GITHUB_SHA}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
    - run: .github/scripts/test/run.sh $REPO:${GITHUB_SHA}

  release:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
    - run: .github/scripts/docker-release.sh $REPO:${GITHUB_SHA} $REPO:latest

  deploy:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    needs: release
    steps:
    - uses: actions/checkout@v2
    - run: .github/scripts/kubectl-config.sh ${{secrets.KUBE_CA}} ${{secrets.KUBE_SERVER}} ${{secrets.KUBE_TOKEN}}
    - run: .github/scripts/kubectl-set-image.sh ipfs-background-service-staging $REPO:${GITHUB_SHA}
    - run: .github/scripts/kubectl-wait-ready.sh ipfs-background-service-staging
    # wait 10 sec for k8s to reroute ingress and check the endpoint
    - run: sleep 10 && curl --fail https://ipfs-service-staging.backend.aragon.org
